//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Booking
    {
        public int booking_Id { get; set; }
        public Nullable<int> product_Id { get; set; }
        public Nullable<int> booking_Quantity { get; set; }
        public Nullable<int> booking_Total { get; set; }
        public Nullable<int> user_Id { get; set; }
    
        public virtual tbl_Product tbl_Product { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
